services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPass
      POSTGRES_DB: moneyOrdersDB